// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using transport;

#nullable disable

namespace transport.Migrations
{
    [DbContext(typeof(transportDbContext))]
    partial class transportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("transport.Models.Country", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("transport.Models.DestinationAdress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("DestinationAdresses");
                });

            modelBuilder.Entity("transport.Models.InitialAdress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("InitialAdresses");
                });

            modelBuilder.Entity("transport.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationAdressId")
                        .HasColumnType("int");

                    b.Property<bool>("Directly")
                        .HasColumnType("bit");

                    b.Property<int>("InitialAdressId")
                        .HasColumnType("int");

                    b.Property<float>("PalletPlace")
                        .HasMaxLength(2)
                        .HasColumnType("real");

                    b.Property<int>("Price")
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    b.Property<int>("PrincipalId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<float>("Weight")
                        .HasMaxLength(10)
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("DestinationAdressId");

                    b.HasIndex("InitialAdressId");

                    b.HasIndex("PrincipalId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("transport.Models.Principal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PrincipalAdressId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrincipalAdressId");

                    b.ToTable("Principals");
                });

            modelBuilder.Entity("transport.Models.PrincipalAdress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("PrincipalsAdresses");
                });

            modelBuilder.Entity("transport.Models.DestinationAdress", b =>
                {
                    b.HasOne("transport.Models.Country", "Country")
                        .WithMany("DestinationAdresses")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("transport.Models.InitialAdress", b =>
                {
                    b.HasOne("transport.Models.Country", "Country")
                        .WithMany("InitialAdresses")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("transport.Models.Order", b =>
                {
                    b.HasOne("transport.Models.DestinationAdress", "DestinationAdress")
                        .WithMany("Orders")
                        .HasForeignKey("DestinationAdressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("transport.Models.InitialAdress", "InitialAdress")
                        .WithMany("Orders")
                        .HasForeignKey("InitialAdressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("transport.Models.Principal", "Principal")
                        .WithMany("Orders")
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DestinationAdress");

                    b.Navigation("InitialAdress");

                    b.Navigation("Principal");
                });

            modelBuilder.Entity("transport.Models.Principal", b =>
                {
                    b.HasOne("transport.Models.PrincipalAdress", "PrincipalAdress")
                        .WithMany("Principals")
                        .HasForeignKey("PrincipalAdressId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("PrincipalAdress");
                });

            modelBuilder.Entity("transport.Models.PrincipalAdress", b =>
                {
                    b.HasOne("transport.Models.Country", "Country")
                        .WithMany("PrincipalAdresses")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("transport.Models.Country", b =>
                {
                    b.Navigation("DestinationAdresses");

                    b.Navigation("InitialAdresses");

                    b.Navigation("PrincipalAdresses");
                });

            modelBuilder.Entity("transport.Models.DestinationAdress", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("transport.Models.InitialAdress", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("transport.Models.Principal", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("transport.Models.PrincipalAdress", b =>
                {
                    b.Navigation("Principals");
                });
#pragma warning restore 612, 618
        }
    }
}
